%% HRL file generated by ERLSOM
%%
%% It is possible (and in some cases necessary) to change the name of
%% the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.


-ifndef(ERLSOM_ANY_ATTRIB_TYPES).
-define(ERLSOM_ANY_ATTRIB_TYPES, true).
-type anyAttrib()  :: {{string(),    %% name of the attribute
                        string()},   %% namespace
                       string()}.    %% value

-type anyAttribs() :: [anyAttrib()] | undefined.
-endif.

-ifndef(ERLSOM_QNAME_TYPES).
-define(ERLSOM_QNAME_TYPES, true).
%% xsd:QName values are translated to #qname{} records.
-record(qname, {uri :: string(),
                localPart :: string(),
                prefix :: string(),
                mappedPrefix :: string()}).
-endif.



-record(root, {anyAttribs :: anyAttribs(),
	common :: 'root/common'(),
	data :: 'root/data'()}).

-type root() :: #root{}.


-record('root/data', {anyAttribs :: anyAttribs(),
	operation :: string() | undefined,
	sequence :: string(),
	parser :: string(),
	time :: string(),
	meter :: 'root/data/meter'()}).

-type 'root/data'() :: #'root/data'{}.


-record('root/data/meter', {anyAttribs :: anyAttribs(),
	id :: string() | undefined,
	function :: ['root/data/meter/function'()] | undefined}).

-type 'root/data/meter'() :: #'root/data/meter'{}.


-record('root/data/meter/function', {anyAttribs :: anyAttribs(),
	id :: string() | undefined,
	coding :: string() | undefined,
	error :: string() | undefined,
	'#text' :: string() | undefined}).

-type 'root/data/meter/function'() :: #'root/data/meter/function'{}.


-record('root/common', {anyAttribs :: anyAttribs(),
	building_id :: string(),
	gateway_id :: string(),
	type :: string()}).

-type 'root/common'() :: #'root/common'{}.